language: generic
sudo: required
env:
    global:
        - secure: "qSKsy0OGJ/GvkD4G9vHO75NZqJbx01sudVZM/A6QORmvKIa05/rdfONkUZNpPIbBWKiDs8LJ3JcWswkbOY+ffo9csdxcrEZAJnJiqiGiwZJXRwITXQneX+IY1w0mMhORg2b8qKVSyRkQ8qXezx78KivLmLl2ViMdpVq34/+jL3RvpJzD8LIyql0/dN2N2pzG4ICAG09XNXlg9LSbLWd9VNKwJjOx7UiTvsTQxiimOOJ/SNWyPM2OT+CuALp8CS85kTUTIyfFPoFdwWHsck1UyJP5Cv7uBYxKtQnF8IgWAZkfrFQptcGnmfFelDvOkWvwJeTQCNH2flwVebnFk/tIt2dR8ae9GP3jL5qWoXmxDofsR9eQS3eKvXdE1Gzx5Gn78gXLyAyWSIduvDEs8VvAyzd/uAcFlqW3zhpx9K2qSq3+KaXaXTk7bmGOc+HNgjvr9LFBl4PtsdAKZOI2EleXm+287pWVVMXE74g8jN/q8UU2MwEqvLymZdTOk8OSeS/oEFcGzUe01YYBr8ibC9b/btEPeLmj42xWiYOcWaDnlZX0EBUkpxqTcMAHIgDZX59AqpUrbUgQyTTQwRINA6H5qCeYIdFdmuFz+MdJ1kdBWWYrd11Pp49T7QMR38U2xaQSNVUFhCHf4SJWZPlUrC7981F/Rf2g+mYeb3trH0EQGM0="

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack

matrix:
  fast_finish: true
  include:
    - env: BUILD=stack GHCVER=7.10.3 STACK_YAML=stack.yaml
      compiler: ": #stack 7.10.3"
      addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}

before_install:
 - rvm get head # workarround for travis issue https://github.com/travis-ci/travis-ci/issues/6307
 - unset CC
 - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
 - ./.travis-setup.sh

install:
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - stack --no-terminal test --only-dependencies

script:
 - set -e
 - stack --no-terminal test --haddock --no-haddock-deps --ghc-options="-Werror"
